#!/bin/bash
################->  are comments
################-> "#SBATCH" (only one "#") are Batch Script commands

################ Verbose mode

#SBATCH --export=ALL

################

################ Change these parameters according to your requisites
# nodes
#SBATCH -N 1

# tasks (threads)
#SBATCH -n 16

# time
#SBATCH -t 30
# time formats =  "minutes", "minutes:seconds", "hours:minutes:seconds", "days-hours", "days-hours:minutes" and "days-hours:minutes:seconds"

# Exclusive (alloc all threads from each node) or shared (alloc only threads set by "-n" parameter)
#SBATCH --exclusive
##SBATCH --shared

################ Please, change this e-mail address to yours

#SBATCH --mail-type=ALL
#SBATCH --mail-user=marco.goedert@edu.pucrs.br

################

#SBATCH --no-requeue

################ Output options

# %%     The character "%".
# %A     Job array's master job allocation number.
# %a     Job array ID (index) number.
# %J     jobid.stepid of the running job. (e.g. "128.0")
# %j     jobid of the running job.
# %N     short hostname. This will create a separate IO file per node.
# %n     Node identifier relative to current job (e.g. "0" is the first node of the running job) This will create  a  separate IO file per node.
# %s     stepid of the running job.
# %t     task identifier (rank) relative to current job. This will create a separate IO file per task.
# %u     User name.
# %x     Job name.

## different files for normal output end error output
##SBATCH -o %x.%j.out -e %x.%j.err

# or

## all output in same file
#SBATCH -o %x.%j.out

################

################ Please, change this directory to your working dir.

#SBATCH -D /home/pp12713/t1

################

################
echo Running on host `hostname`
echo
echo Initial Time is `date`
echo
echo Directory is `pwd`
echo
echo This jobs runs on the following nodes:
echo $SLURM_JOB_NODELIST
echo
echo JOB_ID:
echo $SLURM_JOBID
echo ################

############# Command example, if using MPI

## :> mandelbrot-seq.tempo ; :> mandelbrot-seq.output ; for i in seq 500 5000 500; do gcc -o mandelbrot-seq.c mandelbrot-seq -D NPOINTS=$i -fopenmp; ./mandelbrot-seq 1>> mandelbrot-seq.output 2>> mandelbrot-seq.tempo ; done

################

############# If running a sequential or openMP program
> mandelbrot-seq.output
for i in {500..5000..500}; do echo -n "$i " >> mandelbrot-seq.output ; gcc mandelbrot-seq.c -o bin/mandelbrot-seq-$i -DNPOINTS=$i -fopenmp ; ./mandelbrot-seq >> mandelbrot-seq.output ; done

###> sequencial.tempos
###for i in `cat sizes.txt` ; do echo -n "$i " >> sequencial.tempos ; mpirun -np 1 bin/seq/sequencial-$i >> sequencial.tempos ; echo >> sequencial.tempos ; done

##./mandelbrot-seq


################

echo Final Time is `date`



